# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pimp < Formula
  desc "Command expander and task runner with pattern matching, templating and scripting capabilities"
  homepage "https://pimp.dev"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.5/pimp_0.0.5_darwin_amd64.tar.gz"
    sha256 "ce6e9b050c8633ccc9adc933b0f625c8f8bf35ce51e330c13cc0005579c48fcc"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.5/pimp_0.0.5_darwin_arm64.tar.gz"
    sha256 "5e583b57ce07d59307cd0074bf10aa2833060669668146d7f6cb59b975622e42"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.5/pimp_0.0.5_linux_amd64.tar.gz"
    sha256 "0b01a5e5b5155a65dc238b7acc2318cbd3025a22605ec36988eea3951c9493ad"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.5/pimp_0.0.5_linux_armv6.tar.gz"
    sha256 "fee6bb15a98c518ece573b4f5811f57f049623e296f16e5c9dbbcbd5bb9c8bab"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.5/pimp_0.0.5_linux_arm64.tar.gz"
    sha256 "a88565ab3c4c1cf78f40cb1f732b5aaeb15ef312acf1ac0e266c8f3b92334a2b"
  end

  depends_on "fzf"

  def install
    bin.install "pimp"
  end
end
