# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pimp < Formula
  desc "Command expander and task runner with pattern matching, templating and scripting capabilities"
  homepage "https://pimp.dev"
  version "0.0.6"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.6/pimp_0.0.6_darwin_amd64.tar.gz"
    sha256 "ccc4fa98d4349e82827978908f05787d4a269544d973d7589af555745f26efd8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.6/pimp_0.0.6_darwin_arm64.tar.gz"
    sha256 "f0b843e92b59808428b8d80bb0cb2b96cdd9bb1f12b31e13535bf27c704e3f57"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.6/pimp_0.0.6_linux_amd64.tar.gz"
    sha256 "3eab04f6dcfecba5e9f6d5a63e18a1f21722403712c72586eea5939e2493fd78"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.6/pimp_0.0.6_linux_armv6.tar.gz"
    sha256 "34fd97f38ee645650258c9c34027dc354bff89fecb76c1f25a96718f54b280d6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/aymericbeaumet/pimp/releases/download/v0.0.6/pimp_0.0.6_linux_arm64.tar.gz"
    sha256 "c33e98fda4d54b8b29eca50ee310a46c7e132792c068c6459fe3328b93794f07"
  end

  depends_on "fzf"

  def install
    bin.install "pimp"
  end
end
