# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RunCli < Formula
  desc "Run is a lightweight, standalone tool that manages tasks and processes for you."
  homepage "https://run-cli.org"
  version "0.0.45"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aymericbeaumet/run-cli/releases/download/0.0.45/run-0.0.45-x86_64-apple-darwin.tar.gz"
      sha256 "f146e843f7849a24e8c079bf358e0c1ceddfdfb4dc0a95d4be00c5657364e246"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aymericbeaumet/run-cli/releases/download/0.0.45/run-0.0.45-aarch64-apple-darwin.tar.gz"
      sha256 "499fdfeb1e53c46c5c99619654bda4939df4705a6557a5bc73c338ebf4a2ecc0"

      def install
        bin.install "run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aymericbeaumet/run-cli/releases/download/0.0.45/run-0.0.45-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1751f1aacfb68918ae2e906a50b0480e6bd9297f36f1c9724baaf2d8d236e4a0"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aymericbeaumet/run-cli/releases/download/0.0.45/run-0.0.45-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1fd8b155924decf1acc52951bbaa1be12d3044bcdc13a089c11de82af694df9f"

      def install
        bin.install "run"
      end
    end
  end
end
