# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Run < Formula
  desc "Run is a lightweight, standalone tool that manages tasks and processes for you."
  homepage "https://run-cli.org"
  version "0.0.40"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aymericbeaumet/run/releases/download/v0.0.40/run-x86_64-apple-darwin.tar.gz"
      sha256 "e9aa693a3f99bde48fa98e3b6997345db7f24bc97198ff459d7b14e5c099e8e1"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aymericbeaumet/run/releases/download/v0.0.40/run-aarch64-apple-darwin.tar.gz"
      sha256 "27e11600ee2dac18d045b012122a49d883df2dbc7b5fcb62d070fb4e32e9fd2d"

      def install
        bin.install "run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aymericbeaumet/run/releases/download/v0.0.40/run-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "34fa820c7d49fd158099053a5fc348e0221f3e4fe4fa1fd6529b6c9bb17f8059"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aymericbeaumet/run/releases/download/v0.0.40/run-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "28c9e043affe4e37c8cf73b5819e3b634eb11349f37dfed6e0d6e2de01155fc0"

      def install
        bin.install "run"
      end
    end
  end
end
